### PR TITLE
Fix Sinatra example app

### PR DESCRIPTION
**Pull request by smangelsdorf**
This moves back towards proper support for Sinatra in aaf-lipstick. This support will require `.slim` templates, as the template language has proper support for content helpers which take a block, like:

```slim
= nav_bar do
  ' Content for the nav bar
```

### CODE REVIEW

**Comment by rianniello** [comment]
As discussed, getting a few rubocop errors, (`bundle exec rubocop`). 

```
 bundle exec rubocop                     1 ↵
Warning: unrecognized cop Metrics/ModuleLength found in /Users/rianniello/Projects/aaf-lipstick/.rubocop.yml
Inspecting 47 files
..C............................................

Offenses:

Guardfile:7:9: C: Use %r only for regular expressions matching more than 1 '/' character.
  watch(%r{^spec/.+_spec\.rb$})
        ^^^^^^^^^^^^^^^^^^^^^^
Guardfile:8:9: C: Use %r only for regular expressions matching more than 1 '/' character.
  watch(%r{^lib/(.+)\.rb$}) { |m| "spec/lib/#{m[1]}_spec.rb" }
        ^^^^^^^^^^^^^^^^^^
Guardfile:9:9: C: Use %r only for regular expressions matching more than 1 '/' character.
  watch(%r{^app/(.+)\.rb$}) { |m| "spec/#{m[1]}_spec.rb" }
        ^^^^^^^^^^^^^^^^^^
Guardfile:10:9: C: Use %r only for regular expressions matching more than 1 '/' character.
  watch(%r{^app/(.*)(\.erb)$}) { |m| "spec/#{m[1]}#{m[2]}_spec.rb" }
        ^^^^^^^^^^^^^^^^^^^^^
Guardfile:15:9: C: Use %r only for regular expressions matching more than 1 '/' character.
  watch(%r{^doc/.*\.md$}) { 'spec' }
        ^^^^^^^^^^^^^^^^
Guardfile:23:9: C: Use %r only for regular expressions matching more than 1 '/' character.
  watch(%r{(?:.+/)?\.rubocop\.yml$}) { |m| File.dirname(m[0]) }
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^

47 files inspected, 6 offenses detected

$ bundle exec rubocop -v
0.28.0

```

Ran `bundle update rubocop` (sets to `0.35.1`) to solve it. Not sure if I've done something wrong here.

**Comment by smangelsdorf** [comment]
Oh man, this discussion makes a *lot* more sense now that I know the context.

**Comment by smangelsdorf** [comment]
`Gemfile.lock` is not committed as part of a gem project. You just need to update your dependencies locally to get the newer Rubocop happening.

**Comment by rianniello** [comment]
Tested locally, all works fine.

**Pull request merged**
