### PR TITLE
Allow customisation of auto validation field names

### PR DESCRIPTION
**Pull request by smangelsdorf**
Some fields aren't correctly converted to a readable name automatically, so the app will need to override the descriptive name.

### CODE REVIEW

**Comment by rianniello** [comment]
Interesting how this works with valhammer...

```ruby
class Organisation < ActiveRecord::Base
  include Lipstick::AutoValidation
 
  ...
  valhammer

  @lipstick_field_names = {
      name: 'Object Name',
      description: 'Descriptive Text'
  }
```

image

I'm assuming the @lipstick_field_names is just positional? There is no way to specify the field?

**Comment by smangelsdorf** [comment]
The hash key is the field name

**Comment by rianniello** [comment]
I see. The instructions are:

> If you need to override the way a field is described in validation errors,
> assign the names in the `@lipstick_field_names` variable:

Maybe it could be a bit clearer in the instructions? Or maybe I didn't read it correctly.

**Comment by smangelsdorf** [comment]
How would you suggest it be reworded to make it more clear?

**Comment by rianniello** [comment]
Maybe just something like this "You may override the way a field is described in validation errors. Specify each override with an entry ```fieldname: "description"``` in the ```@lipstick_field_names``` hash." 

... Then give the original example https://github.com/ausaccessfed/aaf-lipstick/pull/21/files#diff-22030a007f43226c6b61f9991ed99a39R269.

**Comment by smangelsdorf** [comment]
Sorted.

**Comment by rianniello** [comment]
Unrelated to this PR:

731 / 732 LOC (99.86%) covered.

Not a big deal just thought I'd let you know.

**Comment by smangelsdorf** [comment]
Yeah, I plan to address that outside this PR.

**Comment by rianniello** [comment]
Cool all looks good. :+1:

**Pull request merged**
